// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwSTBOMqgIuo1zp9pEiF_kPRqK01D26c8',
    appId: '1:1070561496153:web:cff5427cdc532cda7eb548',
    messagingSenderId: '1070561496153',
    projectId: 'moviebooking0168',
    authDomain: 'moviebooking0168.firebaseapp.com',
    storageBucket: 'moviebooking0168.appspot.com',
    measurementId: 'G-GX32Y8TGYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvVaXzBKYrf6BNk7CqouSnAte8PUqlwA',
    appId: '1:1070561496153:android:fbe287e6e27d1a4b7eb548',
    messagingSenderId: '1070561496153',
    projectId: 'moviebooking0168',
    storageBucket: 'moviebooking0168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YG-ybRKxOCGwGGjmO7KuMR99YRDZh5M',
    appId: '1:1070561496153:ios:d84ab80ccf5fc53f7eb548',
    messagingSenderId: '1070561496153',
    projectId: 'moviebooking0168',
    storageBucket: 'moviebooking0168.appspot.com',
    iosBundleId: 'com.example.moviebooking21120168',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2YG-ybRKxOCGwGGjmO7KuMR99YRDZh5M',
    appId: '1:1070561496153:ios:22d4b388d606c41a7eb548',
    messagingSenderId: '1070561496153',
    projectId: 'moviebooking0168',
    storageBucket: 'moviebooking0168.appspot.com',
    iosBundleId: 'com.example.moviebooking21120168.RunnerTests',
  );
}
